### ISSUE TITLE
Would it be possible to make this compatible with PHP 5.3.3 ?

### ISSUE THREAD

**Issue by mcepl** [J-8/ShoppingList_backend#39]
That’s the highest version one can easily get on RHEL/CentOS-6, which is running on (too?) many servers yet.

I am very much willing to test.

**Comment by jklmnn** [comment]
Can you explain what exactly is not supported in PHP 5.3.3? I don't have an overview what works/works not in which version.

**Comment by mcepl** [comment]
I first got:

```
[Thu Sep 17 22:49:21 2015] [error] [client 83.208.252.159] PHP Fatal error:  Call to undefined function password_hash() in /srv/www/mcepl/matej.ceplovi.cz/progs/ShoppingList/INSTALL.php on line 34, referer: https://matej.ceplovi.cz/progs/ShoppingList/INSTALL.php
```

So I have managed to add `require_once('func_inc.php');` to `INSTALL.php`, but apparently there is still something missing:

```
[Thu Sep 17 23:06:37 2015] [error] [client 83.208.252.159] PHP Notice:  Undefined index: item in /srv/www/mcepl/matej.ceplovi.cz/progs/ShoppingList/api.php on line 11
[Thu Sep 17 23:06:37 2015] [error] [client 83.208.252.159] PHP Notice:  Undefined index: count in /srv/www/mcepl/matej.ceplovi.cz/progs/ShoppingList/api.php on line 12
[Thu Sep 17 23:06:37 2015] [error] [client 83.208.252.159] PHP Parse error:  syntax error, unexpected '[' in /srv/www/mcepl/matej.ceplovi.cz/progs/ShoppingList/config.php on line 7
```

**Comment by jklmnn** [comment]
I see. We have changed all occurrences of `var = []` to `var = array()` for compatibility with lower versions of php. Apparently we forgot to do that in INSTALL.php. I will fix that.  
In your case I recommend to change config.php manually by replacing `$*SQL*config = [ ... ];` with `$*SQL*config = array( ... );` .

**Comment by jklmnn** [comment]
This should be fixed with 00333c04b8505fa94a8595a6d38c24890edb46e0.
@mcepl please confirm that the changes I suggested work so I can close this.

**Comment by mcepl** [comment]
You have still not fixed that problem with

```
[Fri Sep 18 11:03:29 2015] [error] [client 83.208.252.159] PHP Fatal error:  Call to undefined function password_hash() in /srv/www/mcepl/matej.ceplovi.cz/progs/ShoppingList/INSTALL.php on line 34, referer: https://matej.ceplovi.cz/progs/ShoppingList/INSTALL.php
```

because you have there `version_compare(phpversion(), '5.3.7',` it should be `5.3.3` to help anything. After changing that to `5.3.3`, INSTALL.php runs (without an error, but the SQLite has not been created yet ??? It would be helpful if at least empty database was created, so that the admin can set proper ACLs, SELinux file contexts, etc. on it).

Also, the Android cliet (from https://f-droid.org/repository/browse/?fdfilter=shop&fdid=org.janb.shoppinglist) still doesn’t work and I have in the Apache log messages (tried running Shopping List twice):

```
==> /var/log/httpd/matej.ceplovi.cz-error_log <==
[Fri Sep 18 11:08:23 2015] [error] [client 83.208.252.159] PHP Notice:  Undefined index: item in /srv/www/mcepl/matej.ceplovi.cz/progs/ShoppingList/api.php on line 11
[Fri Sep 18 11:08:23 2015] [error] [client 83.208.252.159] PHP Notice:  Undefined index: count in /srv/www/mcepl/matej.ceplovi.cz/progs/ShoppingList/api.php on line 12

==> /var/log/httpd/matej.ceplovi.cz-access_log <==
83.208.252.159 - - [18/Sep/2015:11:08:23 +0200] "POST /progs/ShoppingList/api.php HTTP/1.1" 403 58

==> /var/log/httpd/matej.ceplovi.cz-error_log <==
[Fri Sep 18 11:08:28 2015] [error] [client 83.208.252.159] PHP Notice:  Undefined index: item in /srv/www/mcepl/matej.ceplovi.cz/progs/ShoppingList/api.php on line 11
[Fri Sep 18 11:08:28 2015] [error] [client 83.208.252.159] PHP Notice:  Undefined index: count in /srv/www/mcepl/matej.ceplovi.cz/progs/ShoppingList/api.php on line 12

==> /var/log/httpd/matej.ceplovi.cz-access_log <==
83.208.252.159 - - [18/Sep/2015:11:08:28 +0200] "POST /progs/ShoppingList/api.php HTTP/1.1" 403 58
```

**Comment by jklmnn** [comment]
I will change that to 5.3.3.

About the Android client: you should use version 1.0. Version 1.1 is using the experimental branch and has some issues.

I will look that we put the database creation into the INSTALL.php. Currently the sqlite_connector.php checks if the database is available and creates one of necessary.

**Comment by mcepl** [comment]
Still, even with 1.0 I get:

```
[Fri Sep 18 12:40:37 2015] [error] [client 83.208.252.159] PHP Notice:  Undefined index: item in /usr/local/share/ShoppingList/api.php on line 11
[Fri Sep 18 12:40:37 2015] [error] [client 83.208.252.159] PHP Notice:  Undefined index: count in /usr/local/share/ShoppingList/api.php on line 12
```

and the client says that "The server rejected the supplied auth key". I expected that the API key (which is never properly defined anywhere) is something like a password, right? So, value like "tralal8ek" entered both to the INSTALL.php form and the client should be OK, right?

Is there some way how to get more debugging logs for the server script?

**Comment by jklmnn** [comment]
The `Undefined index:...` warnings can be ignored and should not cause any trouble (it's just unclean, we'll change that).
As far as I know we don't have any further logging.
Can you rerun the INSTALL.php and check the auth key again? Since we did not check for your PHP version correctly the auth key might not have been created correctly.
You can try this also from the terminal with `curl http://domain/path/ -d auth=1234 -d function=listall`.

**Comment by mcepl** [comment]
The same (with resetting **everything** to pure 5b9a0831d6e83835d1e6ee3a9f4b603ec237f94f):

```
[Sun Sep 20 21:48:18 2015] [error] [client 83.208.252.159] PHP Notice:  Undefined index: item in /usr/local/share/ShoppingList/api.php on line 13
[Sun Sep 20 21:48:18 2015] [error] [client 83.208.252.159] PHP Notice:  Undefined index: count in /usr/local/share/ShoppingList/api.php on line 14
[Sun Sep 20 21:48:18 2015] [error] [client 83.208.252.159] PHP Notice:  Undefined index: jsonArray in /usr/local/share/ShoppingList/api.php on line 15
[Sun Sep 20 21:48:18 2015] [error] [client 83.208.252.159] PHP Parse error:  syntax error, unexpected '[' in /usr/local/share/ShoppingList/config.php on line 7
```

Are you sure that the encryption of `password_hash` in `func.inc.php` is same as the one produced by the Android app? I have `config.php` on http://mcepl.fedorapeople.org/tmp/config.php (I will remove it with different API key when the wrinkles are fixed, so don't worry about publicizing my secrets, besides the URL is not known).

**Comment by jklmnn** [comment]
It looks like you still have the `[]` in your code.
Apparently @J-8 has upgraded the server to a new version and ha uploaded a new app version. I think you should try it again with this version.

**Comment by J-8** [comment]
Oh darn, I didn't notice I merged to master. Sorry,  really did not want to skip you:/
The current master and release work with app 1.1 and 1.2

**Comment by jklmnn** [comment]
No problem, maybe that already fixed it.

**Comment by mcepl** [comment]
OK, brackets are gone (thank you!), but undefined indexes are still around:

```
[Mon Sep 21 10:47:10 2015] [error] [client 83.208.252.159] PHP Notice:  Undefined index: item in /usr/local/share/ShoppingList/api.php on line 13
[Mon Sep 21 10:47:10 2015] [error] [client 83.208.252.159] PHP Notice:  Undefined index: count in /usr/local/share/ShoppingList/api.php on line 14
[Mon Sep 21 10:47:10 2015] [error] [client 83.208.252.159] PHP Notice:  Undefined index: jsonArray in /usr/local/share/ShoppingList/api.php on line 15
```

(of course, I have reset everything to 100% clean git master 919dc8f37a1b63edd29a79e3acfb8751b7592858 state before testing and restarted Apache to make sure it doesn't have anything in its cache). And I was testing with Android app 1.0.0 from [f-droid](https://f-droid.org/repository/browse/?fdfilter=shop&fdid=org.janb.shoppinglist).

It seems to work with 1.1, but still there are some error/warning messages around:

```
==> /var/log/httpd/hubmaier.ceplovi.cz-access_log <==
83.208.252.159 - - [21/Sep/2015:10:53:57 +0200] "POST /shopping/api.php HTTP/1.1" 200 17
83.208.252.159 - matej [21/Sep/2015:10:54:20 +0200] "PROPFIND /remote.php/webdav/ HTTP/1.1" 207 477

==> /var/log/httpd/hubmaier.ceplovi.cz-error_log <==
[Mon Sep 21 10:54:27 2015] [error] [client 83.208.252.159] PHP Notice:  Undefined index: jsonArray in /usr/local/share/ShoppingList/api.php on line 15

==> /var/log/httpd/hubmaier.ceplovi.cz-access_log <==
83.208.252.159 - - [21/Sep/2015:10:54:27 +0200] "POST /shopping/api.php HTTP/1.1" 200 47

==> /var/log/httpd/hubmaier.ceplovi.cz-error_log <==
[Mon Sep 21 10:54:27 2015] [error] [client 83.208.252.159] PHP Notice:  Undefined index: item in /usr/local/share/ShoppingList/api.php on line 13
[Mon Sep 21 10:54:27 2015] [error] [client 83.208.252.159] PHP Notice:  Undefined index: count in /usr/local/share/ShoppingList/api.php on line 14
[Mon Sep 21 10:54:27 2015] [error] [client 83.208.252.159] PHP Notice:  Undefined index: jsonArray in /usr/local/share/ShoppingList/api.php on line 15

==> /var/log/httpd/hubmaier.ceplovi.cz-access_log <==
83.208.252.159 - - [21/Sep/2015:10:54:27 +0200] "POST /shopping/api.php HTTP/1.1" 200 84
```

**Comment by J-8** [comment]
I am terribly sorry that we are making this so complicated... 
The backend is now updated and works with app 1.1 and the coming 1.2.
We had mixed up some branches.

El 21 de septiembre de 2015 10:50:13 CEST, "Matěj Cepl" notifications@github.com escribió:

> OK, brackets are gone (thank you!), but undefined indexes are still
> around:
> 
> ```
> [Mon Sep 21 10:47:10 2015] [error] [client 83.208.252.159] PHP Notice: 
> Undefined index: item in /usr/local/share/ShoppingList/api.php on line
> 13
> [Mon Sep 21 10:47:10 2015] [error] [client 83.208.252.159] PHP Notice: 
> Undefined index: count in /usr/local/share/ShoppingList/api.php on line
> 14
> [Mon Sep 21 10:47:10 2015] [error] [client 83.208.252.159] PHP Notice: 
> Undefined index: jsonArray in /usr/local/share/ShoppingList/api.php on
> line 15
> ```
> 
> (of course, I have reset everything to 100% clean git master state
> before testing). And I was testing with Android app 1.0.0 from
> [f-droid](https://f-droid.org/repository/browse/?fdfilter=shop&fdid=org.janb.shoppinglist).
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/GroundApps/ShoppingList_Backend/issues/39#issuecomment-141913497

## 

Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by mcepl** [comment]
I think we are already there. If those notices are harmless (and they seem to be), I think this issue can be closed. THANK YOU!

**Comment by J-8** [comment]
You are most certainly welcome :)

**Comment by mcepl** [comment]
Now, let's give you hell on the UX ;)
